ALTER TABLE posts ADD COLUMN read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN like_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN favorite_count INTEGER NOT NULL DEFAULT 0;
